services:
  dev:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /app

  demo:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /app
    command: sh -c "./setup.sh && LANG=C.UTF-8 tmux new-session ./run.sh"
