name: Go lint

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ^1.19
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Lint
      run: make lint

    - name: Vet
      run: make vet